// Franchise,ContactUs page data *****************

export const SOCIAL_MEDIA_LINKS = {
  facebook: 'https://www.facebook.com/share/1YfzqPbwNV/',
  youtube: 'https://www.youtube.com/results?search_query=Falooda+Nation',
  instagram: 'https://www.instagram.com/falooda_nation/profilecard/?igsh=MWVnaDNmOXdtam5hYg==',
  contactnumber: '+91 98462 17021',
  whatsappnumber: '+91 8086288299',
  gmail: 'director@thegreenbay.in',
  linkedin: '',
}
export const Branches = [
  { location: 'Calicut', branches: ['Sks Street', 'Gokulam Mall', 'Hilite Mall', 'Pottammal', 'Lulu Mall'] },
  { location: 'Trivandrum', branches: ['Lulu Mall', 'Mall of Travancore', 'Kovalam'] },
  { location: 'Kochi', branches: ['Kacher', 'Lulu Mall', 'Forum Mall', 'Edappally', 'Thoppumpady', 'Kakkanad'] },
  { location: 'Dubai', branches: ['Al Karama', 'Al Qusais', 'Al Warqa'] },
  { location: 'Kannur', branches: ['SBI Park', 'Source Centre'] },
  { location: 'Lucknow', branches: ['Lulu Mall'] },
  { location: 'Other Locations', branches: ['Thrissur', 'Hyderabad', 'Chennai', 'Kollam', 'Thangassery', 'Perinthalmanna', 'Kottayam', 'Palakkad'] }
];

// Products Page Data *****************

export const faloodaCategories = [
  {
    title: 'The Great Indian Falooda',
    subtitle: 'Chandigarh Ki Gulab (Kulfi Falooda)',
    items: ['Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda'],
    imageUrl: 'https://img.freepik.com/free-photo/lychee-jelly-seasonal-fruit-beautifully-decorated-thai-dessert-concept_1150-23501.jpg?ga=GA1.1.104214007.1745296814&semt=ais_hybrid&w=740',
  },
  {
    title: 'The League of Falooda Nation',
    subtitle: 'Chandigarh Ki Gulab (Kulfi Falooda)',
    items: ['Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda'],
    imageUrl: 'https://img.freepik.com/free-photo/lychee-jelly-seasonal-fruit-beautifully-decorated-thai-dessert-concept_1150-23501.jpg?ga=GA1.1.104214007.1745296814&semt=ais_hybrid&w=740',
  },
  {
    title: 'The Great Indian Falooda',
    subtitle: 'Chandigarh Ki Gulab (Kulfi Falooda)',
    items: ['Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda'],
    imageUrl: 'https://img.freepik.com/free-photo/lychee-jelly-seasonal-fruit-beautifully-decorated-thai-dessert-concept_1150-23501.jpg?ga=GA1.1.104214007.1745296814&semt=ais_hybrid&w=740',
  },
  {
    title: 'The Great Indian Falooda',
    subtitle: 'Chandigarh Ki Gulab (Kulfi Falooda)',
    items: ['Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda', 'Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda'],
    imageUrl: 'https://img.freepik.com/free-photo/lychee-jelly-seasonal-fruit-beautifully-decorated-thai-dessert-concept_1150-23501.jpg?ga=GA1.1.104214007.1745296814&semt=ais_hybrid&w=740',
  }, {
    title: 'The Great Indian Falooda',
    subtitle: 'Chandigarh Ki Gulab (Kulfi Falooda)',
    items: ['Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda', 'Shalimar Falooda', 'Pyaare Gulab Jamun', 'Mumbai Ka King', 'Kesar Pista Falooda', 'Mango Kulfi Falooda'],
    imageUrl: 'https://img.freepik.com/free-photo/lychee-jelly-seasonal-fruit-beautifully-decorated-thai-dessert-concept_1150-23501.jpg?ga=GA1.1.104214007.1745296814&semt=ais_hybrid&w=740',
  }
];

//Home ,Offers page data ********

export const offers = [
  { image: 'images/offers.png' },
  { image: 'images/offers.png' },
  { image: 'images/offers.png' },
];

//Gallery page Data **************


export const reviews = [
  { name: 'Mohammed Shahsad', message: 'Our picks on the menu were worth the try. The ambience is lively. Located in the happening silk street. Worth a try for a relaxing drink.', profilepic:'textimonials/1.png'},
  { name: 'Sana', message: 'Best Falooda ever! Highly recommended', profilepic:'textimonials/2.png'},
  { name: 'hashley s', message: 'They have lot of different and unique range of faloodas, lot of tempting and rich flavours to choose,large portions so totally worth it. I loved every bit of their almond chocolate fudge with ice cream. 😍❤️', profilepic:'textimonials/3.png' },
  { name: 'Zaeem Abdulla', message: 'Another great day spend here with family. One of the best place to chill in calicut. Very cost effective and great taste. They have improved better than before. Without asking owner gave us special discount. Great service.', profilepic :'textimonials/4.png'},
  { name: 'Babu Ganesan', message: 'Nice place to visit for Falooda. Moderate price. Wide varieties available. I would recommend one to visit this place to take Falooda.',profilepic :'textimonials/5.png' },
  { name: 'Ashir Musthafa', message: 'Another great day spend here with family. One of the best place to chill in calicut. Very cost effective and great taste. They have improved better than before. Without asking owner gave us special discount. Great service.',profilepic :'textimonials/6.png' },
  { name: 'Arun Thomas', message: 'Awesome experience.. Great ice-cream',profilepic :'textimonials/7.png' },
  { name: 'Mohammed Shahsad', message: 'Fantastic place and delicious Falooda near Calicut beach. Must visit this wonderful Falooda place and have varieties of Falooda. Personally recommend to taste Passion fruit Falooda, you won’t get disappointed.', profilepic: 'textimonials/8.png' },
  { name: 'Wade', message: 'Really great place with a variety of faloodas 🍨', profilepic: 'textimonials/9.png' },
  { name: 'Aiswarya M', message: 'Variety faloodas available here. Worth money.  Good taste.', profilepic: 'textimonials/9.png' },
  { name: 'Savio Tomy', message: 'Insanely tasty faloodas. Also has a wide selection', profilepic: 'textimonials/10.png' },
  { name: 'Abdul Jameel', message: 'The best place for faloodas. The only falooda joint with a wonderful ambience to sit back and relax too.', profilepic: 'textimonials/11.png' },
  { name: 'Muhammed Basil', message: "I assure falooda nation won't disappointed to you", profilepic: 'textimonials/12.png' },
  { name: 'Ar. Salih clt', message: 'Best falooda available in Kozhikode town.', profilepic: 'textimonials/13.png' },
  { name: 'Neethu siva', message: 'Cool ambience... Supper cool faloodas to beat the heat.... Loads of different flavours to try... "Death by chocolate"" too yumm.... Nice crowd too... Good prompt service... 👍👍💓💓', profilepic: 'textimonials/14.png' },
  { name: 'Faaiz Mohamed Ibrahim', message: "The best faloodas I've ever had...", profilepic: 'textimonials/15.png' },
  { name: 'Anju Balan Laly', message: 'The tasty Falooda I ever had. Nice ambience and good service too.', profilepic: 'textimonials/16.png' },
  { name: 'Jithin Chithra', message: 'Best falooda... Nice. Ambiance', profilepic: 'textimonials/17.png' },
  { name: 'Amrutha Oralakkott', message: 'World of ice creams . good atmosphere and varieties of faloodas are there . Staffs behavior also good,faced bit trouble in car parking .', profilepic: 'textimonials/18.png' },
  { name: 'roshik cp', message: 'Awesome . Good place for falooda lovers.', profilepic: 'textimonials/19.png' },
  { name: 'Krishna Sharma', message: 'Good ambience Value for money delicious food', profilepic: 'textimonials/20.png' },
  { name: 'Fatma Rj', message: 'Awsome place for best faloodas.. Nice atmosphere and service.. Have varieties of flavours and colors of faloodas.. Must visit place in calicut for better falooda option..', profilepic: 'textimonials/21.png' },
  { name: 'Ashiq P P', message: 'Very good place to visit and have a good time', profilepic: 'textimonials/22.png' },
  { name: 'fudail shabnaz', message: 'Wonderful place to go with our family and buddies .', profilepic: 'textimonials/23.png' },
  { name: 'akhil kuruvila', message: 'Great flavours at affordable price', profilepic: 'textimonials/24.png' },
  { name: 'Athul Viswan', message: 'Awsome...!!!! Best choice for falooda.', profilepic: 'textimonials/25.png' },
  { name: 'muhammed Afreedi', message: 'Yummy varieties of faloodas', profilepic: 'textimonials/26.png' },
  { name: 'Sharath Babu', message: 'Mini Falooda was so good and tasty.', profilepic: 'textimonials/27.png' },
  { name: 'Rishad N M', message: 'Best in town for faloodas 😍😍', profilepic: 'textimonials/28.png' },
  { name: 'Harikrishnan T M', message: 'Super cool Falooda....variety menus and very good service... Mostly crowded..🌟🌟🌟🌟🌟', profilepic: 'textimonials/29.png' },
  { name: 'T.R.S. Umesh', message: 'Very pleasant and helpful staff', profilepic: 'textimonials/30.png' },
  { name: 'Asheeb Nihal', message: 'I went there with my Girlfriend👫, She suggested me this place. I love that ambiance. Couples can hangover💑 there and have some tasty faloda😋. Worth it. ✌', profilepic: 'textimonials/31.png' },
  { name: 'Rasnim Usman', message: 'One of the best falooda shope in town', profilepic: 'textimonials/32.png' },
  { name: 'Amruthesh Ck', message: 'There are variety of faloodas and it is very tasty also', profilepic: 'textimonials/33.png' },
  { name: 'daris thomas', message: 'Excellent service, cool and calm atmosphere, tasty falooda 😄 😍 In overall, good experience..😊', profilepic: 'textimonials/34.png' },
  { name: 'Sona Edathil', message: 'I had never taste the special  falooda that i got from here yummy!!', profilepic: 'textimonials/35.png' },
  { name: 'Jithin Rajan', message: 'Good place to get some delicious falooda', profilepic: 'textimonials/36.png' },
  { name: 'Bavin Balakrishnan', message: 'Awesome joint, do come to experience uniqueness of Faloodas Always try the Rabdi Falooda', profilepic: 'textimonials/37.png' },
  { name: 'Sandeep Raj K K', message: 'Different types of faloodas...', profilepic: 'textimonials/38.png' },
  { name: 'Divin Divakar', message: 'Nice place. Recommend anyone who prefer a good falooda.', profilepic: 'textimonials/39.png' },
  { name: 'Manoop Mk', message: 'Have good choice, at reasonable price', profilepic: 'textimonials/40.png' },
  { name: 'Mohammed Hussain', message: 'Various types of fruit salads and shakes ,and  special faloodas', profilepic: 'textimonials/41.png' },
  { name: 'mohammed shafi kunhippa', message: 'Supper and best', profilepic: 'textimonials/42.png' },
  { name: 'Bassam mustafa', message: 'Best ice cream based place. Death by chocolate is best amoung the lot', profilepic: 'textimonials/43.png' },
  { name: 'Jishnu Ramakrishnan', message: 'Will recommend.', profilepic: 'textimonials/44.png' },
  { name: 'Gajanadam R', message: 'Good place for family hangout', profilepic: 'textimonials/45.png' },
  { name: 'Arpith Rk', message: 'Best place to the colourfull band of faloodas ..', profilepic: 'textimonials/46.png' },
  { name: 'Pragati Sharma', message: 'Amazing options for milkshakes. Available in small and large sizes which is great.', profilepic: 'textimonials/47.png' },
  { name: 'Sadath Km', message: 'Very good taste and wide variety of flavours.', profilepic: 'textimonials/48.png' },
  { name: 'Ashru Ashraf', message: 'The best ice cream around calicut', profilepic: 'textimonials/49.png' },
  { name: 'Jaseem Baliyambra', message: "It's really good..a must visit for everyone.. the varsity of fruits, nuts and flavours is awesome!", profilepic: 'textimonials/50.png' },
  { name: 'FaaZ VaaRiK', message: 'Best faloodas in calicut.. Rates on the higher side', profilepic: 'textimonials/51.png' },
  { name: 'Meet Patel', message: 'Very nice place for faloodas and ice cream', profilepic: 'textimonials/52.png' },
  { name: 'Ahammed Farhan', message: 'Nice atmosphere and nice falooda', profilepic: 'textimonials/53.png' },
  { name: 'RS Veeraraghavan', message: 'It is a very nice experience', profilepic: 'textimonials/54.png' },
];

export const images = ["https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1744042246407-f216e4aa80de?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw4fHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1745905932716-431e50eac74b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0fHx8ZW58MHx8fHx8",
  "https://plus.unsplash.com/premium_photo-1699114250038-1c6048f12264?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2fHx8ZW58MHx8fHx8",
]

export const videolinks = [
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
  "https://www.youtube.com/embed/SlpveO908gc",
];
